name: Cypress Tests

on:
  push:
    branches:
      - test
    paths:
      - "blog-nextjs/**"
      - ".github/workflows/main.yml"

jobs:
  cypress-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Electron
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:web
          start: npm run start:web
          record: true
          working-directory: blog-nextjs
          
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_SANITY_DATASET: $${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

  pull-req-main:
    runs-on: ubuntu-latest
    needs: [cypress-electron]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Update main after test branch passed tests
        run: |
          git fetch origin test:test
          git reset --hard test
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
          commit-message: ${{ github.event.head_commit.message }}
          title: PR for ${{ github.event.head_commit.message }}
          body: PR created after running Cypress in test branch. Ready to be merged to main.


    

  # chrome:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node12.18.3-chrome87-ff82
  #   steps:
  #     - name: Cypress Chrome
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
  #         working-directory: blog-nextjs
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  # firefox:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node12.18.3-chrome87-ff82
  #     options: --user 1001
  #   steps:
  #     - name: Cypress Firefox
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: firefox
  #         working-directory: blog-nextjs
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}