name: Cypress Tests

on:
  push:
    paths:
      - "blog-nextjs/**"
      - ".github/workflows/main.yml"

jobs:
  cypress-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Electron
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:web
          start: npm run start:web
          record: true
          working-directory: blog-nextjs
          
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # chrome:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node12.18.3-chrome87-ff82
  #   steps:
  #     - name: Cypress Chrome
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
  #         working-directory: blog-nextjs
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  # firefox:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node12.18.3-chrome87-ff82
  #     options: --user 1001
  #   steps:
  #     - name: Cypress Firefox
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: firefox
  #         working-directory: blog-nextjs
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}